package pkg

var REDACT = []string{
	"GITHUB_TOKEN",
	"GITLAB_TOKEN",
	"GH_TOKEN",
	"CODECOV_TOKEN",
	"SLACK_TOKEN",
	"SLACK_WEBHOOK",
	"HOMEBREW_TAP_GITHUB_TOKEN",
	"NPM_TOKEN",
	"AWS_ACCES_KEY_ID",
	"AWS_SECRET_ACCESS_KEY",
	"AWS_S3_TOKEN",
}
